### ISSUE TITLE
Figure out development process

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/csl-evolution#1]
(work-in-progress)

One big reason CSL development has been at a standstill for the last few years is that we don't have a good open and transparent development process. I would like to figure out the following (we can create additional issues here to discuss these things in more detail):

* We need to figure out communication and flow for making changes to CSL. What does it mean to have consensus, and how do we prevent information overload for people who can't follow everything? We can't have everybody track every CSL repository (e.g. "styles" is way too busy), and even just "schema" and "documentation" might be too much for people outside the core team. The mailing list sucks (hard to search and archive, things go off-track easily, hard to show code, etc.). I think we need something like:
    * Core team creates and/or triages incoming issues on CSL development. I think we should centralize everything into this issue tracker, linking to issues in other repos as appropriate, so that it's enough for non-core folks to keep an eye on this repo.
    * Core team make sure issues contain minimum amount of information to support the request for change. I.e., it's really helpful if we determine early on whether there e.g. are style guides that describe certain requirements we currently don't yet support.
    * Once the need has been established, we can start coming up with one or more solutions.
    * Around this point, we should consult a broader audience, in particular active CSL processor devs, on whether the issue is important enough to address, which solutions are workable, and which one is best.
    * Once some sort of consensus has been achieved, pull requests to the specification and schema can be prepared, reviewed, and merged.
    * Close to release/feature freeze, we should make sure that the total set of changes is consistent, and have another final call for feedback.
* I really think we should switch to a more structured proposal model. Bruce wrote up a template (which I need to dig up), and Apple provides a very nice example with Swift at https://github.com/apple/swift-evolution.
    * See https://github.com/apple/swift-evolution/tree/master/proposals for Swift proposals.
    * See https://swift.org/blog/swift-3-1-release-process/ for Swift's development process.
* We need to make an inventory of what tools need to be updated for a new CSL release, and determine how much time we need to allocate for this, and who will do what. We have our internal tools (validator, visual editor, Travis CI, formatter, etc.) and external ones (CSL processors). We should at least have our own tools updated before we release.
* How to best keep the changelog.
    * Currently, we have one changelog per release (e.g. https://github.com/citation-style-language/documentation/blob/1.0.1/release-notes.txt). Do we want to continue this (starting fresh with each release), or should we switch to a cumulative changelog?
    * Do we need to make any changes to the format? http://keepachangelog.com/en/0.3.0/ has some interesting pointers (e.g. clearly indicating addition, deletions, changes, etc.)
    * Shall we keep the changelog up to date during development? In the past I wrote it close to release, but that's less transparent.
* We should see if we can make use of any of GitHub's features, that we haven't used in the past (project boards, milestones, etc.).
* We need to figure out how to work unit tests into our workflow. Maybe we can add tests to the proposal folders in this repo?

There might be more. I would really like to work this out a bit more, and e.g. write out a development workflow we can follow.

**Comment by bdarcus** [comment]
Here's that template.

https://docs.google.com/document/d/1GTTOl0_Yj9JidrTmOI_pXiKGUqpenFERTP7S4lIBbwo/edit

**Comment by bdarcus** [comment]
Now that we have a good test case of all this, where do we stand now? Doom emacs makes good use of some of the advanced features of github (projects and such) that we might borrow from.

Do we really need to have this separate repo?

**Comment by bdarcus** [comment]
Link to doom [development roadmap](https://github.com/hlissner/doom-emacs/projects/3) project. I'll see about creating something similar here and seeing what we think.

**Comment by bdarcus** [comment]
So the project feature allows you to setup "cards" with auto-triggers, with actions related to PRs, issues, etc.

I think that means we really want this all consolidated on a single repo (schema), and then the conceptual questions is what we should call the different cards.

Doom has cards like "proposed", "rejected", "approved (but no plans yet)", "done (on develop)" and a bundle of future version targets.

Something like that would seem to make sense.

**Comment by denismaier** [comment]
Yeah, that's a nice feature. I agree we should have something similar.
