### ISSUE TITLE
deprecate `entry` and `article`

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#11]
Since `article` and `entry` seem to have been abandoned in favor or more specific item types `entry-dictionary`, `article-journal`, etc. it would seem appropriate to deprecate `entry` and `article`. They don't seem to be used by reference managers.

**Comment by bdarcus** [comment]
I'm not sure; need to think about this.

@adam3smith was right on the discourse forum that these types are effectively legacy. But it's possible there's still value in having them.

Are there any types in any extant formats, including, say, biblatex, that would better match the more general types? If there is, does it even matter practically if we remove them?

And as a general matter, how do we want to think about iterating the list of types? Adding seems pretty straightforward, but deleting?

I'm like 90% sure it'd be OK to deprecate, but I'd prefer to be 100%.

**Comment by denismaier** [comment]
Concerning other formats: biblatex has a generic item type `article`, but there's a field `entrysubtype` that could be used to be more specific. This field is not used by the standard biblatex styles so I'm not sure how common they are in real world biblatex databases, but at least [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc/blob/bd578fd4cc6598ef522f04b839bc7c96b8124949/src/Text/CSL/Input/Bibtex.hs#L1265) seems to use this field to map biblatex to csl-json. An `article` without an additional `entrysubtype` will be mapped to `article-journal`.

The same mechanism should work for `entry-X`, but [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc/blob/bd578fd4cc6598ef522f04b839bc7c96b8124949/src/Text/CSL/Input/Bibtex.hs#L1277) only maps to `entry-encyclopedia`.

RIS seems to have specific types for magazine article and for journal articles, probably also for newspaper articles. (The explanations on [wikipedia ](https://en.wikipedia.org/wiki/RIS_(file_format))are not very detailed, perhaps someone could add to this.)

Generally, I don't think leaving them there would do much harm either. But perhaps the specs could be more detailed, with some explanations about the purpose of each type. The biblatex documentation could serve as a good model here. The use of certain item types could be discouraged, but they could still be left there for compatibility reasons. 

By the way, is there an easy way to check how many styles use `if type="article"` in addition or instead of `if type="article-journal`" etc.? But given that databases prepared with Zotero don't include

**Comment by bwiernik** [comment]
Here was my comment over on Discourse:

> To a degree, I actually see the three “fallback” items as fairly useful and meaningful in their own senses. `post` is widely used for forum posts and social media. `article` has been discussed as a place for preprints, working papers, and other “posted content” (in the CrossRef definition) in repositories. `entry` is useful for things like database entries (e.g., PsycTESTS entries or CIA Factbook) that aren’t really dataset or report. My vote would be for retaining and more clearly defining these three. 

These uses could be given to new types (e.g., `preprint` or `workingpaper` [probably the former given the widest usage]; `entry-database`), but if the types already exist, I'm inclined to leave them as is and address this through better documentation. 

I also realize that `review` is another fallback type. `review` and `review-book` seem pretty redundant. Does a separate book review type need to exist at all? Should that be deprecated in CSL 1.1 and made either formally equivalent (and so treated the same by processors) or removed in CSL 1.2/2.0?

**Comment by denismaier** [comment]
So, in this we'd have three types for specific types of articles and a generic article type that could cover other use cases. Sounds good to me. Zotero et al could then introduce new types like `preprint`, `working paper` that could be mapped to this generic `article` type. But things like these should then be well documented.

And yes, `review` and `review-book` seem redundant, unless `review` is for movies, music.

**Comment by bwiernik** [comment]
So what's the resolution of this now that it's accepted? Just updating the specification to describe more clearly what `article`, `entry`, `post`, and `review` are for? 

I don't think we should just get rid of `entry` and `article` unless corresponding `preprint` and `entry-database` types are introduced. I'm partial to leaving them as general forms of their respective types.

@bdarcus @adam3smith

**Comment by bdarcus** [comment]
To be clear, what we're doing at this points with the project board is
making suggestions, and simultaneously testing the functionality and
workflow.

But given what you say, maybe we should move it back to in review?

>

**Comment by denismaier** [comment]
Done

**Comment by denismaier** [comment]
After having realized that Zotero already maps its generic `document` item type to CSL `article`, I think we should probably leave this as is. (Or introduce a generic item type ourselves...)

So shall we address this situation by defining them more clearly in the specification?

**Comment by bdarcus** [comment]
Hang on: I have a feeling I must have been involved somehow, but I
don't remember.

How did "document" ever get deprecated? Don't we need generic types?

**Comment by denismaier** [comment]
The question was about deprecation `article`. I thought we don't really use that.

But @georgd's [comments at the discourse](https://discourse.citationstyles.org/t/advice-on-legal-citation-style/1632/3?u=denis_maier) forum made me aware that Zotero maps Zotero `document` to CSL `article`.

**Comment by bdarcus** [comment]
I could have sworn at some point we had a "document" type, but don't see it
now.

**Comment by denismaier** [comment]
Ha, good question. Perhaps we should add one, see #40

**Comment by bdarcus** [comment]
I just checked the repo history, and it's never been here.

It was at one point at the very beginning I guess, and I added it for the obvious reason; that we needed fall backs for items that didn't fit with more explicit types.

So yes, I think maybe we should add "document."

I guess I think we should NOT deprecate these since I don't see them presenting any problems. Do either of you?

And there are still things not covered with the current list. How about a newsletter article?

**Comment by adam3smith** [comment]
Before mapping to `article`, `Document` in Zotero was the fallback category, i.e. didn't have any CSL item type associated and would only be called by `else` on `type`. (this just to complete the history; I don't think that's needed and it caused all sorts of problems)

**Comment by denismaier** [comment]
> this just to complete the history; I don't think that's needed and it caused all sorts of problems)

What do you think is not needed? A generic type? Or having a typeless type in Zotero?

**Comment by bdarcus** [comment]
A desire for a generic type [just came up on the forum today](https://discourse.citationstyles.org/t/advice-on-legal-citation-style/1632/3?u=bruce_d_arcus1), with concern about us deprecating "article."

**Comment by georgd** [comment]
It's less a desire for a generic type but rather the quest for a leftover
type usable for a niche case use. Admittedly, I'd have gone with 'generic'
in EndNote but in Citavi and biblatex it would have been something else.
IMO, a generic type makes sense for niche cases like this if the style can
test for the contents of a discriminator field (eg. genre).

bdarcus <notifications@github.com> schrieb am Mi., 27. Mai 2020, 23:20:

**Comment by adam3smith** [comment]
> What do you think is not needed? 

The typeless type. Some sort of generic type makes sense to me

**Comment by bwiernik** [comment]
>  if the style can test for the contents of a discriminator field (eg. genre).

CSL does not have this functionality, and I am skeptical that it should. That would open a huge can of worms and potentially hamper CSL’s strength of avoiding style-specific data entry. 

I don’t really see the need for a “document” type alongside report, brochure, webpage, and article. What would fall into the generic document category but not one of those? “brochure” particularly seems very generic.

For your case, @georgd, I might suggest `brochure` as the best fit (and also least likely to conflict with other styles).

**Comment by georgd** [comment]
> CSL does not have this functionality, and I am skeptical that it should. That would open a huge can of worms and potentially hamper CSL’s strength of avoiding style-specific data entry.

I appreciate a lot the idea of avoiding style-specific data entry and I try to follow that principle as close as possible (hence my request for advice on discourse). But due to the ‘limited’ set of entry types and variables, style-specific data entry is a fact with CSL when it comes to specialized styles (not only juridic ones). Not being able to test for contents of a discriminator variable makes it just a bit more awkward. 

Removing entry types and variables IMO increases the risk of style-specific data entry.

**Comment by denismaier** [comment]
> But due to 
> I appreciate a lot the idea of avoiding style-specific data entry and I try to follow that principle as close as possible (hence my request for advice on discourse). But due to the ‘limited’ set of entry types and variables, style-specific data entry is a fact with CSL when it comes to specialized styles (not only juridic ones). Not being able to test for contents of a discriminator variable makes it just a bit more awkward.
> 
> Removing entry types and variables IMO increases the risk of style-specific data entry.

Hence my suggestion #26 and my enthusiasm for such ideas:
https://discourse.citationstyles.org/t/feature-proposal-custom-schemas-custom-schemas/1578

**Comment by bdarcus** [comment]
Can we close this? I though we ended up wanting to reject?

**Comment by denismaier** [comment]
We'll need to address the purpose of `article` etc. in the documentation.  I'll close this one here as we should add more information about item types anyway.
See https://github.com/citation-style-language/documentation/issues/70
