### ISSUE TITLE
add support for in-text author or "narrative" citation configuration

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/csl-evolution#13]
## Brief Abstract

Arguably the biggest outstanding feature request for CSL is to support in-text "[narrative](https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/parenthetical-versus-narrative)" citations, where the author is moved outside the citation proper. Examples: "Doe (2018)" and "Doe [1]".

In the LaTeX world, this feature is represented in the natbib `\citet` command.

## Style Requirements

Beyond the general support for the feature requested by a lot of users, APA requires [different author rendering](https://owl.purdue.edu/owl/research_and_citation/apa6_style/apa_formatting_and_style_guide/in_text_citations_author_authors.html) when multiple authors are within parenthesis compared to outside of them.

Examples from APA (note the difference in how the "and" is represented in each):

> Research by Wegener and Petty (1994) supported...
> (Wegener & Petty, 1994)

## Level of Current CSL Support 

Partial.

It is possible to build on the suppress author functionality to offer simple author-in-text cases in CSL 1.0. Indeed, `pandoc-citeproc` already does this.

Most CSL implementations, however, require authors to manually write the author name in-text, and then to suppress the author output. Many authors consider this a hassle and prone to errors.

But it is not possible with CSL 1.0 to support any case where the author rendering within the citation is different than when its outside of it (as with the APA example above).

### Suggested

We could add a new `cs:intext` element, a sibling of `cs:citation` with the same RNC pattern, to configure the rendering of the intext author rendering, and then use that output to assemble the narrative citation.

### Alternatives

There are other ways to configure this (multiple `cs:layout` elements per citation, for example), but they introduce other problems that in the end would suggest more invasive CSL changes.

## Compatibility Implications

Processors could ignore the new element, but would have to add new code to support it. Such new code should be relatively uncomplicated, as it would build on existing functionality (like suppress author and substitution).

Some styles (those where the author rendering is different outside of the citation) would need to be updated.

**Comment by dstillman** [comment]
(For background, see https://github.com/zotero/zotero/issues/1580 for our discussion on this in Zotero, which culminated in @fbennett's draft implementation in citeproc-js. I believe this proposal follows the conclusions from that implementation.)

**Comment by bdarcus** [comment]
> (For background, see [zotero/zotero#1580](https://github.com/zotero/zotero/issues/1580) for our discussion on this in Zotero, which culminated in @fbennett's draft implementation in citeproc-js. I believe this proposal follows the conclusions from that implementation.)

That is indeed the intention here, and with the subsequent PR on the schema repo.

https://github.com/citation-style-language/schema/pull/173

**Comment by denismaier** [comment]
Should we move this to the accepted column?  I think we all agree that there's a need for that feature so this could count as accepted. Implementation is a different question, but that should be discussed on the other board. Am I wrong here?

**Comment by bdarcus** [comment]
Done.

I was hoping to implement the automation workflow first, but there's no
reason; it's been discussed to death.

BTW, I just want to emphasize that these citations forms can be implemented
now, with CSL 1.0.

>

**Comment by denismaier** [comment]
Good. You're right. It can be done with CSL 1.0. Do you think it should already be in the next release. If yes, we should move it to a CSL 1.1 board (and remove it from the CSL 2.0 board in any case).

**Comment by bdarcus** [comment]
It was just a suggestion at this point. I think we need more input on the
basic versioning plan.

https://github.com/citation-style-language/csl-evolution/issues/14
