### ISSUE TITLE
define versioning process for styles, schema, etc.

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/csl-evolution#14]
Creating new versions of the schema and spec is technically straightforward.

But how are we thinking to deal with style versioning related to the above, given the thousands of styles we have to maintain?

Will a 1.1 release require completely new style files, that we maintain in parallel with 1.0 styles?

What about 2.0?

@rmzelle suggested [here](https://discourse.citationstyles.org/t/csl-1-2-planning/1476/3) that master would be the current schema, and we'd branch for earlier style versions. 

That makes sense, but I think the below is still relevant.

Could we possibly avoid or minimize the need for separate branches?

Maybe we could add a compatibility section to the spec so we ahead of time make this much easier for us to manage?

This issue should settle and describe whatever the strategy will be.

**Comment by bdarcus** [comment]
https://discourse.citationstyles.org/t/csl-1-2-planning/1476

**Comment by bdarcus** [comment]
https://discourse.citationstyles.org/t/introductions-and-other-supplementary-material/1573/4

**Comment by bdarcus** [comment]
## Observation

I think there are ways to define new CSL syntax that, assuming we mandate this in our spec, could allow implementations to parse CSL 2.0 styles but behave like 1.x (for example, if it takes them some time to support some new features).

Examples: 
- any new attributes or attribute values
- new topic level elements (like the in-text one), and possibly other element changes or additions (though I'd need to this about this more)

## Strawman Spec Compatibility Language

> CSL implementations must cleanly parse (without error):
> 
> - all attributes and attribute values
> - all other [XX} syntax changes and additions

So XX would be bigger syntax changes where we designed them in a such a way that they wouldn't break existing processing code, and where hope would be we could do this with all such changes, so that we wouldn't need to maintain separate 2.0 styles.

Ideally from this perspective, we would commit to guidelines for changes where XX would be all changes, or at least the vast majority.

Test would be whether this would work for our existing backlog of proposals.

In essence, the idea here is to decouple style validation, style versioning and evolution, and style processing to make it all more flexible and resilient.

**Comment by denismaier** [comment]
Need to look more into this, but if we adopt some sort of semantic versioning this will break down to the following principles:

- .x is a new minor version. This will add features, but it will not change the way things are expected to work. At worst, it might be that rendering is incomplete.
  For example, if we add a new item type X in version 1.3., a version 1.2. compliant processor might not process this.
- X. introduces new features that require a more fundamental reworking of the standard.

In that view, the new in-text-element wouldn't be even a new major feature as it's actually strictly additive. It could be included in a new minor version. Perhaps not in 1.1., but it doesn't have to be 1.2.

In turn, this means that every 1.0.1 style should be usuable with any CSL processor until we have 2.0. (In even than there might be ways to introduce compatibility modes.) So there's no need to have 1.1., 1.2. etc. branches. I guess there will simply be styles that don't need the new features while others will require a 1.8. compliant citeproc. The would of course mean that we add an attribute to indicate the "feature level", i.e., if a style depends on a 1.3 compliant citeproc or if it need 1.8. so that it could throw errors if necessary.

**Comment by bdarcus** [comment]
> The would of course mean that we add an attribute to indicate the "feature level", i.e., if a style depends on a 1.3 compliant citeproc or if it need 1.8. so that it could throw errors if necessary.

I was wondering about that, but is it really necessary?

I was assuming we could have the version attribute simultaneously a) define which schema to use for validation, and therefore b) which features the style (may) rely on, with the expectation the processor will know what it can support and how well.

**Comment by denismaier** [comment]
Oh yeah, you're right of course. I forgot the obvious. The version attribute should do the job if we can specify version ranges, and---according to the post you've linked above---that will eventually work in citeproc-rs, once that is ready.

**Comment by bdarcus** [comment]
I don't even think ranges are important.

Consider the intext citation case.

Let's say we implement is in CSL 1.2.

So the version attribute value for an APA style that was incorporating that
element would be "1.2."

It would be a valid CSL 1.2 style if it validated against the 1.2 version
of the schema.

Let's say pandoc-citeproc doesn't support 1.2 yet.

It then simply does what it knows how to do (process citation and
bibliography), and simply ignores the new element.

Or am I missing something?

>

**Comment by denismaier** [comment]
I was actually thinking about this: What happens if in CSL 2.0 we decide to replace the substitute mechanism used for the in-text element with a conditional. But, after reading https://semver.org and @cormacrelf's post linked above I think you're right. We won't need ranges since 1.2 is essentially a range (>=1.2 but < 2).

**Comment by bdarcus** [comment]
No doubt there are changes we might contemplate that would break
processors.

**Comment by denismaier** [comment]
Yeah, but a CSL 2.0 compliant processor should be able to run in "CSL 1.9.4" mode. (Just like today, citeproc-js can run in MLZ mode or in standard CSL mode.

(And there might be transition periods as well. Like, we discourage the use of feature X and advice to use feature Y instead. With CSL 3.0. feature X gets removed.)

**Comment by denismaier** [comment]
> I think there are ways to define new CSL syntax that, assuming we mandate this in our spec, could allow implementations to parse CSL 2.0 styles but behave like 1.x (for example, if it takes them some time to support some new features).

Let's assume this case: We introduce a new condition `if x`. Your citeproc is not yet updated to your version, but you use a style that uses this. What will happen? (Unlike the in-text example, here it is not possible to simply ignore this new node.) 
Do you see a way how this can be handled? Branches (or temporary legacy styles) would be an obvious solution.

**Comment by bdarcus** [comment]
I don't see a way with that case.

So maybe we have three levels of change: minor (adding new attribute values
like for locators), non-breaking moderate (the in-text example), breaking
major (this example).

Is it possible for us to reasonably quickly assign each proposal according
to this sort of categorization?

**Comment by denismaier** [comment]
> minor (adding new attribute values like for locators), non-breaking moderate (the in-text example), breaking major (this example).

The question is: From the level of styles my last example is quite significant. But concerning the schema it's not really major. (It adds a new feature, but it doesn't change the way the things works in a broader sense.)

Nevertheless, we should really try to do such a triage. It would certainly help to get some low hanging fruit done and some issues out of the way.

**Comment by bdarcus** [comment]
Sounds good. 

I think some of the items you moved the proposal review project don't actually involve CSL changes, but changes in Zotero.

**Comment by bdarcus** [comment]
On master vs versioned branches, just a question for people more knowledgeable about git than I:

I noticed the last few years, projects have been using away from using master for primary development, in favor of a "develop" branch.

In that approach, really all changes happen on branches.

**Comment by denismaier** [comment]
For the record: The canonical description for this workflow is probably [here](https://nvie.com/posts/a-successful-git-branching-model/).

**Comment by bdarcus** [comment]
And another thing I'm thinking about:

If we do a 1.1 or 1.2 release, that suggests a new schema (branch) and schema version 

Do we really need to do that for simple changes like variables or item types?

Wondering about doing a minor release for the latter, and then a 1.1 or 1.2 with more substantial changes (like intext).

**Comment by denismaier** [comment]
The question really comes to down to what is considered as a feature in CSL.

It might be absolutely appropriate to add new variables in a minor release (say 1.0.2). But does that make things easier?

**Comment by bdarcus** [comment]
> It might be absolutely appropriate to add new variables in a minor release (say 1.0.2). But does that make things easier?

I think yes; no schema version change.

**Comment by bdarcus** [comment]
I think based on subsequent discussion, we do the following:

- make clear in the specifications that x.x.x schema releases will incorporate new variables
- for x.x style changes, we branch the earlier version of styles before moving to it; for example, we now have a 1.0 branch, that is way out of date. When we're ready to go to 1.1, we merge master on 1.0.

Only open question (for me), is whether we also branch 1.1 and do development there.

BTW, this also makes we wonder, in general, about adopting the `master` vs `develop` branch strategy, which is nicely explained [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

Any view on this @rmzelle, so I can close this?
