### ISSUE TITLE
get rid of `choose`

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#15]
I think we should get rid of choose elements. They are unnecessary and removing them would do no harm. Instead, styles would be more readable. (We could still leave choose optional until 2.0. to make the transition easier.)

**Comment by bdarcus** [comment]
I was just reading someone explaining the elisp "when" macro is syntactic
sugar for a more verbose if/then.

Reminded me of this.

**Comment by bdarcus** [comment]
I'm agnostic, but updating the csl-update.xsl file to remove all choose elements just means adding this:

``` xml
  <xsl:template match="//cs:choose">
    <xsl:copy-of select="*"/>
  </xsl:template>
```

Partial result:

``` xml
    <layout>
      <group suffix=".">
        <text macro="author" suffix="."/>
        <text macro="issued" suffix=" "/>
        <group delimiter=". ">
          <text macro="title"/>
          <group>
            <text macro="container-contributors"/>
            <text macro="secondary-contributors"/>
            <if type="article-journal article-magazine article-newspaper" match="any">
              <text variable="container-title" font-style="italic" text-case="title" font-weight="bold"/>
            </if>
            <else>
              <text variable="container-title" font-style="italic" font-weight="bold"/>
            </else>
          </group>
        </group>
        <text macro="locators"/>
        <group delimiter=", " prefix=". ">
          <text macro="event"/>
          <text macro="publisher"/>
        </group>
        <text macro="access" prefix=". "/>
      </group>
    </layout>
```

**Comment by denismaier** [comment]
I think that looks much better. I don't know if there are technical reasons for wrapping `if` inside `choose`. Someone knows more here? Or why `choose` was introduced in the first place?

**Comment by bdarcus** [comment]
I don't remember, but having the choose wrapper does make explicit the boundaries of the conditional.

**Comment by denismaier** [comment]
One reason I can think of: perhaps it makes working with folding editors more convenient?
Or: is it easier to validate?

**Comment by bwiernik** [comment]
I don't have a strong preference. Whatever is easier to validate `if`, `else-if`, `else` chains.

I don't expect either having it or not having it to be inherently easier to understand for casual style coders working with the Visual Editor. @POBrien333 do you have any thoughts on `choose` in the context of the Visual Editor?

**Comment by bdarcus** [comment]
Makes no difference from a validation POV.

**Comment by adam3smith** [comment]
> having the choose wrapper does make explicit the boundaries of the conditional.

yeah, I wouldn't underestimate the readability issue here, especially for nested conditionals.
That also holds true for the visual editor: adding the choose elements is obviously more tedious because it involves 2-3 more clicks, but because of the clearer boundaries, they are much easier to navigate once they exist, which is the primary way people interact with styles in the visual editor.

That said, I also don't feel strongly about this, but I *am* wondering if the only benefit to this is perceived elegance and a minimal decrease in verbosity if we shouldn't err on the side of conservatism.

**Comment by POBrien333** [comment]
For me it doesn't make much of a difference I'd say, but adam3smith is making good points regarding nested conditionals. Clearer boundaries, clearer to understand.

**Comment by bdarcus** [comment]
> I _am_ wondering if the only benefit to this is perceived elegance and a minimal decrease in verbosity if we shouldn't err on the side of conservatism.

Wondering the same thing. A little additional, unnecessary, verbosity isn't really a practical problem.

And if in doubt in general, we can justify being conservative.

I also don't even think the aesthetic difference is that great.

**Comment by denismaier** [comment]
Okay, I see the unbridled enthusiasm for this proposal ;-) Closing this for now...
