### ISSUE TITLE
test for date parts

### ISSUE THREAD

**Issue by libora** [citation-style-language/csl-evolution#2]
For ISO 690 is important to be able to test if the only year is filled in the date field.
https://forums.zotero.org/discussion/29298/the-conditioned-date-display

**Comment by bwiernik** [comment]
@bdarcus Can you give me triage access to this repo too so I can close some duplicate issues?

**Comment by bdarcus** [comment]
Done. Also on documentation.

>

**Comment by bwiernik** [comment]
Duplicate of https://github.com/citation-style-language/csl-evolution/issues/8 and https://github.com/citation-style-language/schema/issues/32
