### ISSUE TITLE
add "archival-collection" item type

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/csl-evolution#22]
See https://github.com/citation-style-language/zotero-bits/issues/27

**Comment by denismaier** [comment]
Just to be clear: We are talking about the archival-collection as a whole, not a specific item found in a collection?

**Comment by bdarcus** [comment]
Yes.

**Comment by bdarcus** [comment]
I do think there's a reasonable question(, if this is really needed, maybe it's a more general concept like "collection"?

**Comment by bwiernik** [comment]
This is definitely needed. Art History especially cites curated collections and their catalogues often, with unique citation needs. 

This is a proposal and need for a variable `archive_collection` to go with `archive` and `archive_location`. Think:
    - `archive`: Museum name
    - `archive_collection`: Name of collection the item is part of
    - `archive_location`: Box and folder numbers

To avoid confusion, I think this item type should be called `collection`.
