### ISSUE TITLE
add "periodical" item type

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/csl-evolution#23]
See https://github.com/citation-style-language/zotero-bits/issues/23

**Comment by bwiernik** [comment]
Thinking about this one, it is intended to cover two use cases:

1. Entire runs of a periodical
    - e.g., Koslowski, S. W. J. (Ed.). (2010–2015). _Journal of Applied Psychology, 78–84_.
1. A special issue
    - e.g., `Lander, R. (Ed.). (2020). Game-based assessment [Special issue]. _Personnel Assessment and Decisions, 4_(2).`

The first case would not require `container-title`, but the second would. I think `periodical` reasonably will cover both cases, but we should expect `periodical` items to potentially have or not have a `container-title`. This is similar to `song`, which might or might not have an album title.
