### ISSUE TITLE
New condition: Test for variable content

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#26]
In the medium or long term we might want to test for variable content.

```xml
<if variable="title" content="asdf">
</if>
```

**Comment by bwiernik** [comment]
I struggle with this one. I can see the value, but also fear the nightmare of working around typos, multilingual support, flexibility in exact wording, etc.

**Comment by denismaier** [comment]
I understand your concerns and this may indeed be complicated. On the other hand, I envision this not so much as a feature to be used in the official styles, but as a feature that gives end users much more power if they need it, for example to get conditional formatting depending on a value in `genre` or `medium` variables.

One of the main questions is probably how complicated this would be to implement. I imagine it can't be that hard since tests like this one are really at the core of every programming language in existence. But perhaps it's more complicated than it seems... @fbennett  @cormacrelf Perhaps we need some input from implementers here.

**Comment by bwiernik** [comment]
I think the only tests we might support (besides equality) would be tests for matching terms (cf. https://github.com/citation-style-language/schema/issues/240). 

In that case, the same `matches=""` syntax could be used as for equality tests.

**Comment by denismaier** [comment]
Do we actually need a test for this term syntax? Will `term:term` not simply be resolved by the processor? What do you have in mind?

**Comment by bwiernik** [comment]
I don't really have anything in mind. Mostly just don't want to add testing for arbitrary content.

**Comment by denismaier** [comment]
But we could test for terms say `if tested="genre" matches="term:X"`?

**Comment by bwiernik** [comment]
yeah, if we had equality tests, that would be a fairly simple extension beyond variable names.

That would, for example, all for different formatting for tv versus radio broadcasts if that were ever needed.

**Comment by denismaier** [comment]
So equality tests and the terms syntax will also give us content tests. Sounds good.

**Comment by bwiernik** [comment]
Okay, shall we close this issue at this point then?
