### ISSUE TITLE
New condition: Test for equality

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#27]
Another new condition we might want to add later: Test if variable a is equal to variable b.

```xml
<if variable="bookauthor" equals="author">
</if>
```

**Comment by bwiernik** [comment]
This one I am more in favor of. For example, APA style wants `publisher` to be suppressed when `publisher` and `author` are the same.

One wrinkle is how to handle equality for name variables, of which there may be many. Let's say that we have following data:

```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association
```

Should 
```
<if variable="author" equals="publisher">
</if>
```

return TRUE or FALSE here? I'm not sure what, for example, what APA would prefer here. In the case of both a persona and corporate author, I suspect they would say TRUE:

```
author: Smith || John
author: American Psychological Association
publisher: American Psychological Association
```

If we decide that it should return FALSE, then that makes this a problem:
```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association; National Center for Measurement in Education; Society for Industrial-Organizational Psychology
```

So, we would need `publisher` to behave like a `names` variable and accept multiple values. That is probably a good idea anyway.

**Comment by bwiernik** [comment]
This one I am more in favor of. For example, APA style wants `publisher` to be suppressed when `publisher` and `author` are the same.

One wrinkle is how to handle equality for name variables, of which there may be many. Let's say that we have following data:

```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association
```

Should 
```
<if variable="author" equals="publisher">
</if>
```

return TRUE or FALSE here? I'm not sure what, for example, what APA would prefer here. In the case of both a persona and corporate author, I suspect they would say TRUE:

```
author: Smith || John
author: American Psychological Association
publisher: American Psychological Association
```

If we decide that it should return FALSE, then that makes this a problem:
```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association; National Center for Measurement in Education; Society for Industrial-Organizational Psychology
```

So, we would need `publisher` to behave like a `names` variable and accept multiple values. That is probably a good idea anyway.

**Comment by bwiernik** [comment]
This one I am more in favor of. For example, APA style wants `publisher` to be suppressed when `publisher` and `author` are the same.

One wrinkle is how to handle equality for name variables, of which there may be many. Let's say that we have following data:

```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association
```

Should 
```
<if variable="author" equals="publisher">
</if>
```

return TRUE or FALSE here? I'm not sure what, for example, what APA would prefer here. In the case of both a persona and corporate author, I suspect they would say TRUE:

```
author: Smith || John
author: American Psychological Association
publisher: American Psychological Association
```

If we decide that it should return FALSE, then that makes this a problem:
```
author: American Psychological Association
author: National Center for Measurement in Education
author: Society for Industrial-Organizational Psychology
publisher: American Psychological Association; National Center for Measurement in Education; Society for Industrial-Organizational Psychology
```

So, we would need `publisher` to behave like a `names` variable and accept multiple values. That is probably a good idea anyway.

**Comment by denismaier** [comment]
Yes, I guess it's quite common that certain fields are not printed if they have the same values as some other field, for example no book-author if book-author  and author are the same.

But you raise good points here. It's really necessary to define what equality really means here. (It might be also possible to think of a test like `<if variable="publisher" is-part-in="author">`. But that needs to be really thought through.

Are there any general objections to this? If not, I suggest we start discussing these questions when preparing a later release.

**Comment by bwiernik** [comment]
(As a specific vote in favor of this, this is the one major APA rule that CSL currently can't accommodate.)

**Comment by denismaier** [comment]
> So, we would need publisher to behave like a names variable and accept multiple values. That is probably a good idea anyway.

Absolutely; perhaps we should even have allow some sort of name like behaviour, like so:
```
publisher:
  name: XY Press
  place: location
```

That would be necessary for formatting multiple publishers correctly, and be a cleaner solution than that [CSLm hack](https://citeproc-js.readthedocs.io/en/latest/csl-m/#id77).
(But that's a different story.)

**Comment by denismaier** [comment]
superseded by https://github.com/citation-style-language/schema/issues/285
