### ISSUE TITLE
add fields to to `name` data model, new `names` behavior

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#29]
Following up on https://discourse.citationstyles.org/t/extensions-to-name-data-label-or-alternate-name-role/1609/4

I propose three additions to the `name` data model used in CSL-JSON and accessible in styles:

### Changes for 1.1

1. `alternate`: For things like names in alternative scripts, online usernames, inferred authors
1. `label`: To override the default label used for a name
    1. This would permit complex descriptive role information used in styles like APA and MLA
1. `is-uncertain`: Indicates that a name is uncertain or inferred.
    1. This would be testable using `is-uncertain-name` (analogous to `is-uncertain-date`)

### Changes for 2.0?

APA has distinct styling rules for personal/individual versus non-personal/organizational authors. In-text citations for individual authors are always short-form. Group authors should be long form with short form in parentheses the first time the name is used, then short form there after (e.g., `(American Psychological Association [APA], 2019)` first, but `(APA, 2010)` subsequently). For that, I suggest:

1. Add `short` to the `name` data model
    1. A short form of the name for single-field/non-personal names (e.g., "APA" for "American Psychological Association")
1. Add `individual` and `organization` as children of `name` providing separate formatting for individual and organizational authors.
1. Allow `form="short"` for organizational authors.
1. Add `form-subsequent` to permit different first and subsequent formats for appearance of the name. 
1. Add `form="long-short"` to render a non-personal name as `Long Name [Short Name]`.
1. Update the spec to indicate that personal names with only one part (e.g., Plato) should be entered in "family", not like non-personal names.

Edit: Move `is-uncertain` here.

**Comment by denismaier** [comment]
Occassionally, there are requests for replacing recurring authors/names with "idem" etc. The most recent being https://forums.zotero.org/discussion/83362/no-gender-in-zotero-excludes-eadem-and-eaedem
Another one: https://forums.zotero.org/discussion/comment/348124#Comment_348124

This cannot really work without a way to indicate the gender of a name. (And a control structure to test for equality: author==bookauthor; that could also be useful for your "publisher==corporate-author" case.)

What do you think? Could this be addressed in a data model overhaul? (UI constraints aside...)

(Sidenote: Citavi suppports that using a relational data model where names are saved in a table. This also ensures that names are always written in the same way. But that is of course more a Zotero question and out of the scope of CSL.)

**Comment by bdarcus** [comment]
> This cannot really work without a way to indicate the gender of a name.

That seems a pretty big barrier.

**Comment by bwiernik** [comment]
Idem is one bibliographic convention that I really wish would just go away, so I’m not enthusiastic about the complexity increase this would entail.

**Comment by denismaier** [comment]
What about the opposite of `is-uncertain`: anonymously published but known authorship.
Also, what about pseudonyms?

**Comment by bwiernik** [comment]
Those would both fall under the “alternative” field I think

**Comment by bwiernik** [comment]
Superseded by https://github.com/citation-style-language/schema/issues/291

**Comment by bdarcus** [comment]
> 1. Add `short` to the `name` data model

Any reason not to add this to 1.1?

**Comment by bwiernik** [comment]
No, planning on it. Just haven't gotten around to writing up pull requests based on https://github.com/citation-style-language/schema/issues/291 and https://github.com/citation-style-language/csl-evolution/issues/7
