### ISSUE TITLE
Institutional author abbreviation or short form

### ISSUE THREAD

**Issue by libora** [citation-style-language/csl-evolution#3]
The journal Water Alternatives (http://www.water-alternatives.org/index.php/guide) has in guide for authors:

Example of organisation as author or government publications:
IIMI (International Irrigation Management Institute). 1993. Advancements in IIMI's research 1992. Colombo, Sri Lanka: IIMI. 
[in the text, refer to IIMI (1993)]

Name of an author is "Short-form/abbreviation (full-name)" but reference must be "short-form/abbreviation".
https://forums.zotero.org/discussion/57035/institutional-author-abbreviation-or-short-form

**Comment by bwiernik** [comment]
Will be addressed by https://github.com/citation-style-language/schema/issues/291
