### ISSUE TITLE
Split main-title and sub-title

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#31]
Citeproc-js has support for splitting `title` variables into `title-main` and `title-sub`. I think we should formally adopt this in CSL.

There's been some discussion about this [here](https://discourse.citationstyles.org/t/handling-main-sub-title-splits-citeproc-js/1563).

I particularly like to highlight @georgd's suggestion to use an inheritable attribute like `title-sub-delimiter`.

**Comment by bwiernik** [comment]
This would be useful, but what exactly is the function of `title-sub-delimiter`? Is it to control the rendering of items in the bibliography or the splitting of a single `title` variable into `title-main` and `title-sub`, or both?

For example, APA style calls for titles to be rendered with whichever punctuation it is published with. However, it does call for subtitles to have their first letter in uppercase, with the subtitle being defined as after a colon or period (but not em dash).

That raises two questions:

1. We would also need an attribute `normalize-sub-delimiter="true"`. (true if yes, false to render the title without normalization).
1. How to handle styles that recognize multiple symbols as `title-sub-delimiter`?
    - The APA case isn't really a problem--just use `title-sub-delimiter=":"` and assume that any titles delimited with a period are entered with the letter following the period capitalized.
    - But what about styles that recognize colon, period, and em dash? Are there many of those that we would need to worry about that?

**Comment by bwiernik** [comment]
One other wrinkle, what about titles with multiple subtitles? For example, `High School Musical: The Musical: The Series`. All of delimiters here should be normalized/have the first letter after in uppercase.

**Comment by denismaier** [comment]
I thought `title-sub-delimiter` can be used to make style coding a bit easier. So instead of having to create a macro

```
<macro name="title-full">
<group delimiter=". ">
<text variable="title-main/>
<text variable="title-sub/>
</group>
</macro>
```

and having to repeat that for `container-title`, `volume-title`, `collection-title`, you'll just have `<style title-sub-delimiter=". ">`

Concerning the splitting: citeproc-js already seems to have pretty good heuristics to split titles into segments, so I don't think we need an attribute here. What we need though is an easy way to satisfy different style requirements concerning the punctuation between title and subtitle. Most German styles use periods, I think other European styles as well (Italian?, French?). CMoS prescribes colons. Exclamations marks and question marks usually override these prescriptions.

So, I'd say the main question periods vs. colons. (I'd also replace dashes, but I'm not sure if that can be done in all cases.)

Regarding `normalize-sub-delimiter="true"`: We could also normalize only if `title-sub-delimiter` is present. If not, do nothing. Would that work? (I took a [shot at it earlier](https://github.com/Juris-M/citeproc-js/issues/135#issuecomment-624127290), and it seems feasible. Most likely replete with problems, but anyway... The additional background to the question is variant handling in Juris-M.)

Multiple subtitles: I don't know. I think, CMoS uses colons for subtitles and then semicolons.

**Comment by denismaier** [comment]
Regarding the question about dashes: Chicago doesn't replace dashes with colons. I don't know if that is a general rule.
A possible solution could be `normalize-sub-delimiter="period dash"` vs `normalize-sub-delimiter="period"`, i.e., only normalize certain characters.

Regarding multiple subtitles: The splitting mechanism doesn't seem to cover this currently. I don't know how complicated that is. On this, we'll need input from @fbennett.

**Comment by denismaier** [comment]
Rereading the Frank's original post over on Discourse and on Zotero-dev, I think these are the next steps/decisions to be made:

1. Should `title-main` and `title-sub` be accepted? 

2. If yes, is the splitting in the domain of citeprocs, or should that be done by the reference manager proper? I don't have strong opinions about this, but that citeproc-js already has a working implementation of that mechanism speaks for the first. If so, we should then ask Zotero devs to call citeproc-js with the necessary flag. (Of course, that means other citeprocs will have to be updated accordingly.)

I guess that would solve the most pressing demands, and formalize a feature that already exists in the most widely used citeproc.

The next step would then be to decide over `normalize-sub-delimiter`, `title-sub-delimiter`, `text-case=uppercase-subtitle`, and so on...

Anything wrong with that approach?

**Comment by bwiernik** [comment]
I think `title-main` and `title-sub` should be adopted. I think that the citeproc should split `title` if that is all that is provided. 

With that in mind, several behaviors have to be defined:
1. How to render `title` if the data provides `title-main` and `title-sub` (what delimiters to use)
1. How to split `title` into `title-main` and `title-sub`
1. Whether and how to normalize delimiters 

There are several variations across styles that need to accommodated:

1. Styles vary in what delimiters are used to split (e.g., APA splits on `—`, Chicago does not; Chicago splits on `; or,` and `, or,` but most other styles do not)
1. Some styles (e.g., Chicago) normalize delimiters, other (e.g., APA) do not
1. Styles vary in whether second+ subtitles use the same or a different delimiter (e.g., `;` instead of `:`).

<details>
<summary>With these in mind, here is my proposal:</summary>

1. Add `title-main` and `title-sub` as variables.
1. **Data structure:** In CSL JSON, `title` can be provided as an array with `full`, `main`, and `sub` elements. `sub` can be be an array with multiple subtitles. `full` should always be specified to 
1. **Parsing by citeproc:** If `title-main` and `title-sub` are not supplied in the data, the citeproc will derive them from `title` following these rules (based on existing citeproc-js behavior):
    1. Split the title based on the inheritable attribute `title-split`. Options for this attribute are:
        - `"simple"`: Matches `. `, `: `, `:: `, `! `, `? `
        - `"full"`: Matches the values for `"simple"`, plus `—` and `; `
        - `"chicago"`: Matches the values for `"simple"`, plus `; ` and `[;,] or[,:]`
        - (Not exactly sure about `; `. APA, e.g., doesn't clearly mention it, but every use a semicolon in a title I have seen is to delimit a subtitle.)
        - (Possibly could just have `"regular"` [`"full"` above] and `"chicago"` if that would suffice.)
    1. `title-main` is the text before the first delimiter. `title-sub` is an array of the text following each delimiter.
    1. If both `title` and `title-main` are provided and `title-main` matches the beginning of `title`, only split the delimiter following the `title-main` text if any. (This provides an override to prevent the standard splitting behavior if needed.)
1. **Rendering title:** `<text variable="title">` renders `title-main` followed by `title-sub`. 
    - The delimiter is set by the inheritable attribute `title-delimiter`, a text string. `title-sub` renders all of its elements, with the delimiter set by the inheritable attribute `title-sub-delimiter` (the same as `title-delimiter` if empty). 
    - Don't add another delimiter if one is already at the end of the previous title chunk (e.g., don't add ":" to the end of 'title-main` "Dude, where's my car?").
    - Child elements `<main>` and `<sub>` control text styling for each part separately (e.g., ABNT rules about `title-main` in bold but `title-sub` in regular face).
    - This might warrant a new `cs:title` element sibling to `cs:text`.
1. **Normalizing delimiters:** If the inheritable attribute `normalize-sub-delimiter` is true, `. ` and `: ` delimiters are changed to the values specified by `title-delimiter` and `title-sub-delimiter`. Other delimiters are left unchanged.
1. **Text casing:** When calling `<text variable="title">`:
    1. `text-case="title"` title casing is applied to `title-main` and each element of `title-sub`
    1. `text-case="capitalize-subtitle"` the first letter of `title-main` and each element of `title-sub` is capitalized
    1. Other text cases have the current behavior.
1. **Other titles:** All of the above apply to all `title` variables (`container-`, `collection-`, `volume-`, etc.)

</details>

<details>
<summary>Links to relevant citeproc-js behavior:</summary>

  - [here](https://github.com/Juris-M/citeproc-js/blob/5bbf98b9ed534d778d72e8f8257894b580feee90/src/load.js#L740)
  - [here](https://github.com/Juris-M/citeproc-js/blob/5bbf98b9ed534d778d72e8f8257894b580feee90/src/load.js#L826)
  - [here](https://github.com/Juris-M/citeproc-js/blob/5bbf98b9ed534d778d72e8f8257894b580feee90/citeproc.js#L874)
  - [here](https://github.com/Juris-M/citeproc-js/blob/5bbf98b9ed534d778d72e8f8257894b580feee90/citeproc.js#L1236)

</details>

**Comment by denismaier** [comment]
Thanks for this well thought-out proposal. A think that looks sound, and most of it could be adopted immediately, right?

A couple of questions:

> The delimiter is set by the inheritable attribute `title-delimiter`, a text string. `title-sub` renders all of its elements, with the delimiter set by the inheritable attribute `title-sub-delimiter` (the same as `title-sub-delimiter` if empty).

That should be "the same as `title-delimiter` if empty", right?

> **Normalizing delimiters**: If the inheritable attribute `normalize-sub-delimiter` is true, . and : delimiters are changed to the values specified by `title-delimiter` and `title-sub-delimiter`. Other delimiters are left unchanged.

1. `normalize-title-delimiters` is perhaps a better name for the attribute?

2. So, there won't be a way to change dashes as well? What about using `normalize-sub-delimiter="period dash"` vs `normalize-sub-delimiter="period"` or similar here? Or we could use the same options here as for `title-split`? (`normalize-sub-delimiter="chicago"` would be misleading though as Chicago does not split here...)


> * Child elements `<main>` and `<sub>` control text styling for each part separately (e.g., ABNT rules about `title-main` in bold but `title-sub` in regular face).
> 
> * This might warrant a new `cs:title` element sibling to `cs:text`.

So something like this?

```xml
<title variable="title">
  <main font-weight="bold" />
  <sub/>
</title>
```

In terms of compatibility problems, how severe will the impact of this be? What do you think?

I think we might add most of this in a backwards compatible way, `cs:title` is a bigger change of course, but the other additions probably won't change existing behaviour if `normalize-sub-delimiter` (or however we call that attribute) defaults to `false.` Perhaps we could also add `title-split="false"` to preserve complete backwards compatibility. But styles could then gradually adopt the new features as needed.

Regarding `cs:title`: Would it be possible to allow both versions, i.e., to render titles with `cs:text` or with `cs:title`? (More or less like we do with numbers.) That would not break existing behaviour, styles will continue to work, but the more advanced way to render titles is available if someone---as in the ABNT case---needs it.

**Comment by bwiernik** [comment]
> That should be "the same as title-delimiter if empty", right?

Yes. Fixed.

> normalize-title-delimiters

Agreed. 

> Normalize dashes as well?

I'm not sure the expected behavior here. Chicago wouldn't normalize dash, but does normalize to colon/semicolon. We should look at some German and Brazilian styles to see what they would do with a dash. If dash is normalized, then if `"chicago"`, the dash would not be normalized.  

> So something like this?

No need for the empty `<sub/>` element. This would work just like `<et-al/>` in `cs:names`—optional children to modify default formatting. 

> Perhaps we could also add title-split="false"

`title-split` doesn't really matter unless you call `text-case="capitalize-subtitle"` or `normalize-title-delimiters="true"`. Only change to existing behavior would be that `text-case="title"` generalizes to capitalize a stop word if it is the first word of a subtitle, rather than only if follows a colon, period, exclamation mark, or question mark. That's a minor enough change to not worry about backwards compatibility.

> Would it be possible to allow both versions, i.e., to render titles with cs:text or with cs:title? 

Yes, it was my intention that `cs:title` would be optionally usable for styles requiring separate main and subtitle formatting, but that `cs:text` would be more common. Adding `cs:title` would mean that we don't have to change `cs:text` to permit any children.

**Comment by denismaier** [comment]
Ok. That all looks good to me. So, the only open question is if normalization should only affect colons/periods/semicolons, or dashes as well. Right?

Other opinions about the proposal? Anyone sees problems here?

**Comment by denismaier** [comment]
[Interesting post on the SBL Blog](https://sblhs2.com/2018/07/12/dashes-in-german-titles/): They don't normalize dashes. The dashes in the example are clearly part of the subtitle though, i.e., they don't separate title and subtitle.

**Comment by bwiernik** [comment]
Given that post and Chicago's convention, I would say we probably can probably (1) not normalize dashes to periods/colons, but (2) apply the dash normalization (e.g., to an en dash instead of two hyphens) that citeproc-js currently does when uppercase subtitles in enabled.

**Comment by denismaier** [comment]
So what do we do here? Given that citeproc-js has much of this already, we could add this soon, perhaps together with the in-text feature? Or even earlier?

**Comment by denismaier** [comment]
@bdarcus @adam3smith @rmzelle 
What do you think?

**Comment by bdarcus** [comment]
I think this is one of those long issue threads that's difficult to pick up if one hasn't been following.

Maybe it's time for someone to submit a PR to schema, that includes in the message impact on existing styles, etc. and we can review the details there?

**Comment by denismaier** [comment]
@bwiernik What do you think? Can this already be transformed in a PR?

**Comment by bwiernik** [comment]
Sure. I'm working on the variables terms one. Do you want to put together a PR for this one?

**Comment by denismaier** [comment]
I'll try. Need to get a bit more knowledge of Relax NGC schemas first... Well, actually I would think that the schema additions aren't the main problem here. As in the issues raised by Normal Walsh, the difficult part will probably be codifying the processor behaviour.

**Comment by bwiernik** [comment]
Schema first, then Docs, seems like a good workflow so far

**Comment by bdarcus** [comment]
> I'll try. Need to get a bit more knowledge of Relax NGC schemas first... Well, actually I would think that the schema additions aren't the main problem here. As in the issues raised by Normal Walsh, the difficult part will probably be codifying the processor behaviour.

The RNC is super easy; just add to this list:

https://github.com/citation-style-language/schema/blob/master/csl-variables.rnc#L57

Maybe in the PR comment itself you can propose spec language?

**Comment by denismaier** [comment]
Fine, the new title-variables are easy.

But we will also need at least these attributes:
`title-split`, `normalize-sub-delimiter`, `title-delimiter` and `title-sub-delimiter`. Just add them to `cs:style`?

Also, we'll need `text-case="capitalize-subtitle"`. (Should be easy as well.)

And: What shall we do regarding the suggested `cs:title` element? Include it already in this PR?

**Comment by bwiernik** [comment]
Yes.

**Comment by denismaier** [comment]
Concerning replacing dashes again: The SBL Handbook 6.1.3.1 says: 

> In citing a book, therefore, punctuation must often be added and may even be altered: except when double punctuation would result (e.g., following a question mark or exclamation point), a colon (not a period, semicolon, comma or dash [!]) should separate title and subtitle. This rule may be applied regardless of the punctuation or lack thereof on the title page and regardless of the language of the book."

However: "Retain any dashes that are present in the original title."

So, we do have to replace dashes that separate title and subtitle, but we should not touch them if they are part of the title. Ouch...

**Comment by bwiernik** [comment]
In every example that SBL has given, they seem to treat dashes as not separating a title and subtitle. So they seem to follow Chicago-like behavior.

**Comment by denismaier** [comment]
But you don't know if the other examples have had dashes instead of colons before, do you?

**Comment by bwiernik** [comment]
They generally want dashes to be retained:
> Retain any dashes that are present in the original title.

When operating on heuristics, I don't think we can discern when a dash is a title or subtitle. Given that they should not always be normalized, I think we should just not normalize. If a user needs more control, they can supply `title-main` and `title-sub` as separate variables.

**Comment by denismaier** [comment]
> When operating on heuristics, I don't think we can discern when a dash is a title or subtitle. Given that they should not always be normalized, I think we should just not normalize. If a user needs more control, they can supply `title-main` and `title-sub` as separate variables.

I am not sure that this works. Just an example:

```
title: A title with a dash---and a subtitle
title-main: A title with a dash
title-sub: and a subtitle
```

If we normalize only colons and periods, it won't help to add `title-main` and `title-sub` explicitly. Citeproc-js will grab the dash, and use that as the joining character in the reassembled title.  Instead, using `title-main` will help in a situation where the heuristics are to aggressive:

```
title: A title with a dash---that is part of the title
title-main: A title with a dash---that is part of the title
```

Is my understanding correct so far?

If yes, this gives us two options:

1. Don't support dashes at all.
2. Extend `normalize-title-delimiters`: Allow more options instead of simply `true`/`false`. Perhaps `colons-periods`/`colons-periods-dashes` or `false`/`simple`/`full`?

**Comment by bwiernik** [comment]
Closing; what remains is documentation in the linked issue.

**Comment by fbennett** [comment]
I haven't been following the discussion at all closely. If someone can add a fixture or two to the test suite that exercises the desired behaviour, I can make the processor fall in line.

**Comment by bwiernik** [comment]
@denismaier Could you put together some fixtures?

@fbennett They are pretty much based on your existing uppercase subtitles code.

**Comment by denismaier** [comment]
@bwiernik Yes, will do!
