### ISSUE TITLE
Rename `annote` to `annotation`

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#32]
I think "annote" (which doesn't seem to be a word: https://www.merriam-webster.com/dictionary/annote) should be changed to "annotation" (https://www.merriam-webster.com/dictionary/annotation).

_Originally posted by @rmzelle in https://github.com/citation-style-language/documentation/pull/73#issuecomment-621596569_

Yes, `annotation` is a much better name for the variable. 

But wouldn't that be backwards incompatible, and therefore something for a later version? 

On the other hand, I don't know how severe that would be. Changing the styles to use the new variable should be trivial, and GUI applications should just change how they map their own fields to CSL variables. (CSL does not know aliases for variables, right?)

**Comment by rmzelle** [comment]
> But wouldn't that be backwards incompatible, and therefore something for a later version?

Yes.

> CSL does not know aliases for variables, right?

Not yet. (and it probably shouldn't)

CSL JSON (https://github.com/citation-style-language/schema/blob/master/csl-data.json) also has found some unexpected uses, so it's not just CSL processors we're concerned with in terms of backwards compatibility.

**Comment by bwiernik** [comment]
I made a comment in the other thread about problems with `annotation`. There is potentially a fair amount of meta-analysis data in the wild using `annote`, so unless aliases are adopted, my preference would be to leave `annote` as-is.
