### ISSUE TITLE
add new creator types

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#33]
There are some new creator types we should add, primarily for media item types (television broadcasts, films, etc.), along with accompanying terms.

  - `producer`
  - `writer` (as in a screenwriter)
  - `executive-producer`
  - `contributor` (e.g., 'Smith, Adam (with John Paul Jones)')
  - `narrator` (as for an audiobook)

APA style would also like 
  - `host` (as for a podcast or other regular broadcast)
  - `guest` (for a broadcast)
  - `principal-investigator` (for a grant)
  - `co-investigator` (for a grant)

There have also been requests before for:
  - `compiler`
  - `cartographer`
  - `performer`

## Alternative to many new variables

@bdarcus has rightly expressed annoyance at what are essentially type-specific forms of "author". These make writing styles more complex. An approach to streamline the complexity would be to adopt the `names` data model described [here](https://github.com/citation-style-language/csl-evolution/issues/29) that includes a `label` field. 

With that model, `producer`, `writer`, `narrator`, `host`, `guest`, `principal-investigator`, `co-investigator`, `cartographer`, and `performer` could all `author`, with a label with the appropriate term. 

This could be implemented in clients by adding the appropriate term label to their CSL JSON (e.g., Zotero could add `term="producer"` to an `author` entered as **Producer** for a TV Broadcast item). A text field could allow users to override the label for more complex descriptions (e.g., "Guest Expert", perhaps "Principal Investigator" and "Co-Investigator").

If we did that, only `contributor` and `executive-producer` would need to be added as distinct creator types (even `executive-producer` could be `editor (term="executive-producer")`. `director` could be deprecated and interpreted as `author (term="director")`

**Comment by denismaier** [comment]
I think it's beyond dispute that we need those new creator types. 

The more flexible approach using role annotations certainly has its merits. But even then, we'd nevertheless have to define those descriptive terms, right?

**Comment by bwiernik** [comment]
Yes, we would need terms at a minimum.

**Comment by bwiernik** [comment]
Superseded by https://github.com/citation-style-language/schema/issues/293
