### ISSUE TITLE
add new terms for APA/MLA

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#34]
APA has a variety of standard terms that should be added to enable better use of apa.csl across locales. MLA has a similar set of terms, but I'm less familiar with that style. 

In addition to terms for [new types of creators](https://github.com/citation-style-language/csl-evolution/issues/33) and a general term for each item type (e.g., `patent`, `map`, `song` [which might be localized in English as "Audio recording"]), I think the following should be added:

1. album
1. advance-online-publication
    - This is distinct from `in-press` or `forthcoming`
1. personal-communication
1. `article` 
    - for "Article No. e012345"
1. `preprint`
1. `working-paper`
1. `original-work-published`
1. `on`
    - for a track **on** an album (rather than **in** an album)
1. `review-of`
1. `film`
1. `video`
1. `television-series` 
1. `radio-broadcast`
1. `podcast`
1. `special-issue`
1. `special-section`

Perhaps also 
1. `number`
    - currently `term="issue"` (localized in English as "No.") is used, which works, so perhaps this one is unnecessary

Adding these would go a long way toward making APA transportable across locales, and it could even eliminate some requirement of users to manually enter `genre` into their data (e.g., a client could automatically add `term:podcast` to a **Podcast** `boadcast` items). (The `term:term` behavior is a new propsoal`.)

**Comment by bwiernik** [comment]
@denismaier These issues I opened this morning are the major changes for APA we talked about in January

**Comment by denismaier** [comment]
These looks quite reasonable, yes. Can we accept those en bloc or do we need to discuss each term?

Concerning 10-14: These are item types, right? So if we add those types we should also add corresponding terms.

**Comment by denismaier** [comment]
Concerning MLA: Should we check that now? (I currently don't have access to the manual so I can't check.) Or should we add those terms (if they exists) in a later release?

**Comment by denismaier** [comment]
Another terms related question: In German styles, there are sometimes different terms for journal volumes and for book volumes. For a book volume you'd use the term "Band", for a journal volume "Jahrgang". Is there a reasonable way to cover this.

**Comment by bwiernik** [comment]
10-14 aren’t distinct item types. They are `motion_picture` or `broadcast` respectively. These terms would either be:
  1. variations on the theme that a style might use (like with in-press versus forthcoming). Some styles might use “Motion picture”, some might use “Video” as a term.
  2. Something that could work with a syntax like `term:video`. If a user or client inserts that into a field, it would render with the localized term instead of the literal text.

(2) is definitely a bigger change that wouldn’t have to happen now. 

@adam3smith Do we have an MLA manual?

**Comment by denismaier** [comment]
I see.

Just to clarify, I do have the MLA manual. It's in my office, and I just don't know when I'll be there again.

**Comment by bwiernik** [comment]
I can check to see if I can get access to an MLA book. 

For volume, perhaps replacing `volume` with `volume-book` and `volume-journal` (or just adding those). Then, German or multilingual styles could call the specific one. `cs:label` would need to check the item type and choose the appropriate term for the label.

**Comment by denismaier** [comment]
> For volume, perhaps replacing `volume` with `volume-book` and `volume-journal` (or just adding those). Then, German or multilingual styles could call the specific one. `cs:label` would need to check the item type and choose the appropriate term for the label.

Or: Allow conditions in terms?

```xml
<locale xml:lang="de">
  <terms>
    <term name="volume" form="short">
	  <choose>
	  <if type="article-journal">
	  	<single>Jg.</single>
	    <multiple>Jg.</multiple>
	  </if>
	  <else>
	    <single>Bd.</single>
	    <multiple>Bde.</multiple>
	  </else>
    </term>
  </terms>
</locale> 
```

**Comment by denismaier** [comment]
What do you mean with "`cs:label` would need to check the item type and choose the appropriate term for the label."

**Comment by bwiernik** [comment]
`cs:label` provides the relevant term for the variable being used, with the requested form and correct pluralization. So,

```
<label variable="volume" form="short"/>
<text variable="volume"/>
```

would become “vol. 1” or “vols. 1–3”. Accommodating locales with multiple words for “volume” would need a way to select the appropriate term based on the item type.

Perhaps a conditional in the locale definition is the cleanest way to do that? I’m not sure if that would cause problems. @adam3smith @rmzelle do you foresee anything?

**Comment by bwiernik** [comment]
MLA and Chicago have specific forms they want for "special issue" and "special section" https://github.com/citation-style-language/zotero-bits/issues/36

**Comment by denismaier** [comment]
Any suggestion how this could be handled?
