### ISSUE TITLE
add text-case="capitalize-subtitle"

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#35]
APA title formatting rules call for the first letter of words following a period or colon to be in uppercase. citeproc-js has a workaround for this by having an `uppercaseSubtitles` flag, which Zotero switches on for styles with ID starting with "apa" and a whitelist of other styles. It would be good to incorporate this formally into CSL. 

This could be combined with the `title-sub-delimiter` attribute here to control how to parse subtitles/where to uppercase them.

**Comment by denismaier** [comment]
Good idea. Probably better than the current ad hoc solution.

**Comment by denismaier** [comment]
Closing. This is covered by #31
