### ISSUE TITLE
Add `hereinafter` variable

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#37]
CSL-M has a `hereinafter` variable for special shorttitles/abbreviations/short citation forms of particular items. Wouldn't it make sense to include this in CSL? (I don't think that adding the variable poses particular challenges in itself. The main challenge is probably how this variable will be populated by users...)

**Comment by georgd** [comment]
In how far is this necessary next to title-short? Are there cases where you would need different shorttitle and hereinafter in one entry?

I can imagine that a hereinafter variable is useful if a user wants to override the title-short entry on a per document basis in order to disambiguate. But that would require Zotero et al. to implement mechanism and interface for that functionality. (IIRC that’s what Juris-M does).

**Comment by denismaier** [comment]
> In how far is this necessary next to title-short? Are there cases where you would need different shorttitle and hereinafter in one entry?

You will probably use one or the other.
`title-short` is used for, well, a shorter version of the title. `hereinafter` renders a shortened version of the whole citation, i.e., depending on your style replace author and title(-short), or author and year.

This is used in certain disciplines a lot, e.g., philosophy or literature, where you'll have citations like this:

> Adorno, Theodor W. Negative Dialektik, in Gesammelte Schriften, by Theodor W. Adorno, ed by. Rolf Tiedemann, Suhrkamp: Frankfurt am Main, 2003, vol. 6, henceforth cited as ND.

You are right with your comment concerning concerning setting this on a per document basis. I think this will most likely be the main problem here. How will users use this variable, given that the abbreviation filter does not work with Zotero at the moment. (As you note, it works with Juris-M, and you can also use abbreviations per document with pandoc, but unfortunately not with Zotero.)

**Comment by denismaier** [comment]
@bdarcus @bwiernik other opinions?

**Comment by p-heckler** [comment]
> Adorno, Theodor W. Negative Dialektik, in Gesammelte Schriften, by Theodor W. Adorno, ed by. Rolf Tiedemann, Suhrkamp: Frankfurt am Main, 2003, vol. 6, henceforth cited as ND.

Couldn't ND be a `title-short` variable here? I feel that what is needed is not so much a variable as a new `hereinafter` term in order to do this without having to use a `prefix`.

**Comment by denismaier** [comment]
> > Adorno, Theodor W. Negative Dialektik, in Gesammelte Schriften, by Theodor W. Adorno, ed by. Rolf Tiedemann, Suhrkamp: Frankfurt am Main, 2003, vol. 6, henceforth cited as ND.
> 
> Couldn't ND be a `title-short` variable here? I feel that what is needed is not so much a variable as a new `hereinafter` term in order to do this without having to use a `prefix`.

I don't see how this could work.

As said above, `title-short`is used for, well, a shorter version of the title. `hereinafter` renders a shortened version of the whole citation, i.e., depending on your style replace author and title(-short), or author and year.

To stick with this example:
In an author-note style you'll usually use author + title-short for subsequent citations. That would be "Adorno, Negative Dialektik" here. If you use `title-short` for ND here, you'll use the ability to just use a shorter version of the title.

Like here:
Hicks, Making the Case for a Sociocultural Perspective on Information Literacy
=> here you'll use `title-short` to get:
Hicks, Making the Case

But in the Adorno example above, I just want:
ND

**Comment by p-heckler** [comment]
If I understand correctly, this `hereinafter` variable would supersede the usual subsequent citation (in whichever format it is) with an optional output. In your exemple,  
Hicks, Making the case -  and  - 
ND 
can cohabitate as valid subsequent citations in the same document, right? If so, I see your point. That being said, the name `hereinafter` might have the potential to confuse users since in many styles, the expression is used to announce a subsequent short title, eg:
Hicks, Making the Case for a Sociocultural Perspective on Information Literacy, herinafter Making the case
where the subsequent is 
Hicks, Making the Case. 
Something along the lines of `short-citation` might be more transparent.

I remain convinced that a `hereinafter` term is (also) needed.

**Comment by bwiernik** [comment]
If this were implemented, it should be separate from `title-short`. It would be used in styles in a form something like this:
```
<if variable="hereinafter">
  <text variable="hereinafter"/>
<if>
<else>
  {regular subsequent text}
</else>
```
See the example in the CSLm spec: https://citeproc-js.readthedocs.io/en/latest/csl-m/#hereinafter-extension

That said, `hereinafter` is not like similar variables, such as `title-short` or `citation-label`, in that, in CSLm, its value is set in a per-document basis, rather than by either the style or the input data. It seems like this variable would be quite difficult to handle adequately without the accompanying behavior of Abbreviation Filter.

**Comment by denismaier** [comment]
> That being said, the name `hereinafter` might have the potential to confuse users since in many styles,

I've just used that name in the proposal as CSLm also uses that name for this variable. That said, I have no objections against using another name for this, e.g. `shorthand` (like in biblatex).

Anyway, @bwiernik is absolutely right with his assertion that such a variable is not like similar variables, and that this poses an obstacle to adding this at the moment.

**Comment by denismaier** [comment]
Thinking about this again, I propose we look into this for 1.1. I assume this variable could be handled without too many problems in systems like pandoc. @jgm What do you think?

In Zotero it's obviously more difficult. But it's a bit a chicken and egg problem. Without such a variable, there's one reason less for implementing abbreviation filter like functionality. But I'm optimistic that this could be solved somehow  @dstillman ?

Also, having this variable without accompanying features in e.g Zotero won't be a huge deal either. The way this will be handled in styles just means that there's no problem if the variable is missing.

**Comment by bwiernik** [comment]
My understanding of uses for `hereinafter` are one of three things:
1. Shortening an institution name on subsequent uses: e.g., "American Psychological Association" becomes "APA"
1. Shortening a case or legislation name to a shorthand
1. Shortening a full citation to a form like "MLG86"

The first would be handled by the proposed change to the `names` data structure (https://github.com/citation-style-language/csl-evolution/issues/7) to have short-forms specified for institutional authors. The second is `title-short`. The third is `citation-label`, which could be automatically generated or added to an item's data (I expect a user's manually-specified citation label won't change from paper to paper.)

So, what is hereinafter for beyond these cases?

**Comment by denismaier** [comment]
What I was thinking of is actually no.3. Just that it won't be auto-generated and that only specific items will be cited by label. 
It should be possible to define them on a per-document basis. (The label content won't probably change, but you will need a label for one item in one document, for another item in another document.)

**Comment by denismaier** [comment]
If we use `citation-label` we might still want to add corresponding terms: `henceforth`: "henceforth cited as"

**Comment by bdarcus** [comment]
So this is just a shortened form for the citation or name, to allow more concise subsequent representations.

Right?

So why a variable?

And what's the demand for this? Seems like perhaps one of those archaic conventions that may not be needed?

**Comment by bwiernik** [comment]
It’s fairly common in, for example, commentaries on a work in stats or math to do something like:
`Smith, Jones, and Tester (2009) [henceforth SJT09] argued …`

It’s arguably useful when you are going to refer to the authors 100 times in the course of the comment (personally I’m not a fan). I think this use is reasonably well-covered by `citation-label`. If the user only wants to abbreviate a specific citation in this way, that could be accomplished through some conditional logic or more simply by typing a suffix. I imagine most users are happy to just type “SJT09” in text on subsequent citations; it seems more difficult to accomplish this through CSL/something like the Jurism Abbreviations Filter.

**Comment by denismaier** [comment]
Yes, the use-case is exactly as per @bwiernik's description. That's quite common in certain disciplines, say, e.g. literature or philosophy. When you are writing about one author or even one book, you will want to use shorthands for this particular work or all the works of this author.

How do you think that could be handled by typing a suffix @bwiernik ?

Typing the shorthand manually might work in some cases, but it fails if you also need to use "ibid."

Anyway, I agree that there's probably no need for a new variable: `citation-label` seems to do the job. So we'll "only" need to find a way to define this variable on a per document basis.

For pandoc, I imagine a solution where you have your `references.yaml` file, and shorthand definitions in the document metadata,

```yaml
bibliography: references.yaml
citation-labels: 
  - id: adorno2003NegativeDialektik
    citation-label: ND
  - id: SmithJonesTest2009
    citation-label: SJT09 
```

Maybe something for a filter, or for the new citeproc library @jgm ? Do you think something like this could work?

In Zotero/Word this will be more complicated, of course, but perhaps one could just load a json file with the labels from the word processor plugin, so a full abbbreviation filter wouldn't be needed.

**Comment by bwiernik** [comment]
> How do you think that could be handled by typing a suffix @bwiernik ?

I just meant the user would manually add "hereafter, "SJT08" as a suffix to the citation, then type SJT08 as regular text later in the document. 

I'm not really too concerned about an interface for this. Supplying a `citation-label` in pandoc can just be adding CSL YAML to the header or editing the input bibliography file. In word processor GUI programs like Zotero, this could be a checkbox/text field in the citation interface to add a citation-label to use thereafter for an item. 

But honestly, if the improvement over manually typing this to support ibid, that seems not worth the effort. Using two different forms of shortened subsequent citations seems like terrible reader-hostile practice. All of this seems like it could be accomplished using existing CSL style features. For example, test for `citation-label` and `if position="subsequent"`, then use `citation-label` for items having one or a general subsequent citation form for other items. If the concern about that is that the citation processor automatically generates citation-labels, then the style could specify a new empty citation-label format so that only explicitly set citation labels exist.

**Comment by denismaier** [comment]
> > How do you think that could be handled by typing a suffix @bwiernik ?
> 
> I just meant the user would manually add "hereafter, "SJT08" as a suffix to the citation, then type SJT08 as regular text later in the document.

Hmm, that feels a bit like going back to the days of preparing bibliographies manually. You'd have to be sure to have the suffix that introduces a shorthand really on the first citation of a particular item.

> 
> I'm not really too concerned about an interface for this. Supplying a `citation-label` in pandoc can just be adding CSL YAML to the header or editing the input bibliography file.

That's true. But if you use BBT, you can really only make these edits as the final step.

> In word processor GUI programs like Zotero, this could be a checkbox/text field in the citation interface to add a citation-label to use thereafter for an item.

Good idea.

> 
> But honestly, if the improvement over manually typing this to support ibid, that seems not worth the effort. Using two different forms of shortened subsequent citations seems like terrible reader-hostile practice. 

Maybe true.

> All of this seems like it could be accomplished using existing CSL style features. For example, test for `citation-label` and `if position="subsequent"`, then use `citation-label` for items having one or a general subsequent citation form for other items. 

Yeah, that's how I thought it can be done with `citation-label`. Really just like your example above:

```xml
<if variable="citation-label">
  <text variable="citation-label"/>
<if>
<else>
  {regular subsequent text}
</else>
```

> If the concern about that is that the citation processor automatically generates citation-labels, then the style could specify a new empty citation-label format so that only explicitly set citation labels exist.

I wasn't aware of that: Is the idea that processors always generate labels? I thought so they should only do this when explicitly instructed to do so (using the proposed [new citation-label syntax](https://github.com/citation-style-language/csl-evolution/issues/30)).

**Comment by p-heckler** [comment]
> If we use `citation-label` we might still want to add corresponding terms: `henceforth`: "henceforth cited as"

I second that. Whichever variable is used, the term "hereinafter" must be set as a plain text prefix. Given how common it is used in styles, a dedicated term would be a cleaner solution for single-locale styles and the only solution for multi-locale styles, where hard-coding is not an option.

This might be a separate issue entirely, as an `hereinafter` term can be used with a number of variables beside `citation-label` (especially `title-short`). Is it worth opening a new thread in Schema for this?

**Comment by bwiernik** [comment]
> I wasn't aware of that: Is the idea that processors always generate labels? I thought so they should only do this when explicitly instructed to do so (using the proposed new citation-label syntax).

Oh, I suppose that would be a better idea. Currently citeproc-js and citeproc-rs automatically generate a citation label for each item when `citation-label` is called. We would need to amend that behavior in the spec when the new syntax is added.

**Comment by bwiernik** [comment]
>  Is it worth opening a new thread in Schema for this?

@p-heckler No, please keep discussion of this issue in one place.

**Comment by bwiernik** [comment]
So, let's imagine a user is writing a style where they want to use a `citation-label` for subsequent citations. They specify this:
```
<choose>
  <if position="subsequent" variable="citation-label" match="all">
    <text variable="citation-label/>
  </if>
  <else-if position="subsequent">
    <group delimiter=" ">
      <text macro="author-short"/>
      <date variable="issued" date-parts="year"/>
    </group>
  </else-if>
  <else>
    <group delimiter=" ">
      <group delimiter=" ">
        <text macro="author-short"/>
        <date variable="issued" date-parts="year"/>
      </group>
      <group prefix="[" suffix="]" delimiter=" ">
        <text term="henceforth"/>
        <text variable="citation-label"/>
      </group>
    </group>
  </else>
</choose>
```

That work?

**Comment by denismaier** [comment]
Yes. That should work if `citation-label` is not automatically generated.
Perhaps we will need multiple henceforth terms: `henceforth`, `henceforth-cited-as`

**Comment by bwiernik** [comment]
Do we really need two `henceforth` terms? What application does this have other than for subsequent citations? If we want to have stock localization for both "henceforth" and "henceforth cited as", that could be long/short forms of `henceforth`?

**Comment by denismaier** [comment]
I thought one is for introducing `citation-label`, the other can introduce short forms of institutions: 
American Psychological Association (henceforth APA), Style Guide, 7th edition (henceforth cited as APA7).

**Comment by denismaier** [comment]
But using `@short` for this distinction should work!
