### ISSUE TITLE
make style ids immutable

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/csl-evolution#38]
We should [resolve this](https://discourse.citationstyles.org/t/proposal-make-style-ids-immutable/1478/27) soon.

My thinking is [here](https://discourse.citationstyles.org/t/proposal-make-style-ids-immutable/1478/23?u=bruce_d_arcus1), which means no schema change; just documentation, etc.

But I have not followed that thread, so may have missed something.

We could also tighten the constraints on the id element in 1.1. Not sure that's necessary though.

**Comment by bwiernik** [comment]
Closed by https://github.com/citation-style-language/documentation/pull/82

**Comment by bwiernik** [comment]
@bdarcus Can you give me triage rights here, then we should be able to close or migrate every issue in this repo at this point.

**Comment by bdarcus** [comment]
I just gave the reviewers team triage rights here.
