### ISSUE TITLE
add more international identifiers?

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#39]
Currently CSL has two types of ISO identifiers: ISSN and ISBN. It also includes major identifiers used in citations: DOI, PMCID, PMID.

There are several other ISO identifiers that are analogous to ISSN and ISBN. These appear to be important for citation and cataloging in fields like musicology (e.g., https://github.com/citation-style-language/zotero-bits/issues/28).

They are:
  - ISWC (for a musical work itself)
  - ISMN (for a musical notation/score)
  - ISRC (for an audio or visual recording)
  - ISAN (for an audiovisual work itself)
  - ISCI (an identifier for an archival collection)

(Page 25 here is helpful: https://www.ismn-international.org/files/Web_ISMN_Users_Manual_2016.pdf)

Should we add these other 5 identifier variables?

**Comment by denismaier** [comment]
I don't see why we shouldn't add them. What are the costs? (If there are any...)

**Comment by georgd** [comment]
Not an ISO identifier but also with international use: the ECLI (https://github.com/citation-style-language/schema/issues/131)

**Comment by denismaier** [comment]
I'll move this to accepted for a later release. If there are any objections, please shout...
