### ISSUE TITLE
Accepted/in print flag and term

### ISSUE THREAD

**Issue by libora** [citation-style-language/csl-evolution#4]
A lot of journals allow citing the documents (typically articles/conference papers), which are accepted for publication but still not published.  We need the term for these cases (something like "in press"/"in print"/"accepted for publication") and the flag to use this term.
Now, the text like "in print" can be filled in the date field in the Zotero, but if the guide for authors describes another term, then there is no way to change it by the CSL processor. In CSL 1.01. is similar construction `is-uncertain-date`.

**Comment by bwiernik** [comment]
The `status` variable already exists and is implemented for such cases in several styles. There are also terms for `in press` and `forthcoming`. "in press" should come from `status`, not `issued`.

An approach to make this most robust and usable might be to force a controlled vocabulary on `status`, such as [`in-press`, `early-online`, `corrected`, `retracted`]. I think those four statuses might pretty well cover all of the use cases in existing styles. "in print" and "accepted for publication" would be localizations of the term `in-press`. `early-online` would get localized in APA, for example, as "Advance online publication". More diverse statuses for things like manuscripts should probably stay as free-entry in `genre` following existing usage.

With that, that would require three terms:
* `early-online`
* `corrected`
* `retracted`

**Comment by bwiernik** [comment]
See also https://github.com/zotero/zotero/issues/637

**Comment by denismaier** [comment]
I think we should close this in favor of the more general proposal https://github.com/citation-style-language/schema/issues/240
