### ISSUE TITLE
add generic type `document`

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#40]
We don't have a generic item type at the moment. Should we add one? @bdarcus @bwiernik

**Comment by bwiernik** [comment]
I’m not sure exactly what this would entail that is not covered by report, brochure, article, and webpage

**Comment by bdarcus** [comment]
In archival work, one comes across documents that are not clear fits for
any of the more specific types we have.

Think flyers or hand-written notes.

Basically, there are probably hundreds of citable document types extant.
And if a format does not support the one you need, you either need to map
horizontally, to an equally specific but wrong type, or you map vertically;
to something more generic.

In the original CSL design, I required generic default types templates, two
of which were "document" and "article."

The processor I wrote actually had a fallback system that would map items
to those templates, if there weren't specific ones available.

Not saying we recreate that; just explaining.

**Comment by bwiernik** [comment]
But that’s what `brochure` is for, no?

**Comment by bdarcus** [comment]
For which; newsletter?

What about notes?

In neither case is brochure an intuitively obvious match for me.

**Comment by bwiernik** [comment]
(To be clear, I meant `pamphlet`.)

`pamphlet` is for "things like fragments, historical documents, or other unusually-published or ephemeral works"

https://discourse.citationstyles.org/t/what-is-a-pamphlet/1474/2

A newsletter or set of notes both seem to be covered by that.

**Comment by bdarcus** [comment]
I guess in the end it seems a little silly to have the "entry" and "article" more generic types, but not "document."

But if there's substantial uncertainty or dcebate about this, we could always just leave this here for comment, and come back to it later.

@denismaier - what do you think after this discussion?

**Comment by denismaier** [comment]
I think having a generic type is a good idea. But I'm not sure if we need this in addition to `article`. Perhaps it's just a naming problem, like `article` being a too specific name? `document` or even `misc` might be good names. Perhaps we can just rename `article`?
If that causes problems, I wouldn't mind adding `document` as well.

**Comment by bwiernik** [comment]
Why don't we add `document` and formally designate `article` to capture things like working papers and preprints (CrossRef "posted content")?

**Comment by bdarcus** [comment]
+1
