### ISSUE TITLE
add condition: year < 2000

### ISSUE THREAD

**Issue by denismaier** [citation-style-language/csl-evolution#41]
As per @georgd [here](https://discourse.citationstyles.org/t/advice-on-legal-citation-style/1632/13?u=denis_maier):

> At somoe places, years should be formtatted with two digits if year < 2000 and with four digits otherwise. Am I right in assuming that that’s not possible? At least I haven’t found it in the documentation. It’s a requirement that I met in various (legal and non-legal) styles already, especially when dealing with EU sources. 

I think that sound like a reasonable suggestion. Other opinions about this? Anyone else has seen that requirement before?
If we add this: Perhaps it should be done in a not so specific way. Rather than `if after-2000` perhaps something like "`if date-range="1900-1999"` which would be adaptable to other requirements.

**Comment by denismaier** [comment]
Moving over to schema

**Comment by adam3smith** [comment]
> If we add this: Perhaps it should be done in a not so specific way. Rather than if after-2000 perhaps something like "if date-range="1900-1999" which would be adaptable to other requirements.

(Please more this along to the schema ticket): I don't have a strong opinion on adding this, but I've seen requirements that make the inclusion of publisher place dependent on year (I think pre1900) so if we do this I think it should definitely be more flexible than just after-200
