### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#5]
@rmzelle Can you make a Wiki for csl-evolution as a central location for putting consensus changes to CSL and/or the Zotero data model?

**Comment by adam3smith** [comment]
I think we said the gh wiki feature is too confusing and we'd rather do this in a centralized markdown file? We could give you write access.

**Comment by bwiernik** [comment]
Okay, I don't think I followed that discussion to its end from earlier this year.

**Comment by rmzelle** [comment]
I was hoping to adopt a similar workflow used for Apple's Swift programming language, where proposals are stored within the repository itself. That gives us much, much better notifications, tracking, and version control than a wiki.

Hopefully Frank, Sebastian, and I will be meeting in person later this month, and we can perhaps kickstart a new release cycle and decide on some workflow things.
