### ISSUE TITLE
Evolution process

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/csl-evolution#6]
1. Every proposal is in a separate markdown file and follows a template (details tbd) but based on https://docs.google.com/document/d/1GTTOl0_Yj9JidrTmOI_pXiKGUqpenFERTP7S4lIBbwo/edit 
Files should be consecutively numbered (001, 002, 003, etc.) and contain a short summary. E.g. `003-add-standards-item-type.md`
2. Every proposal has an issue linked to it, which is used for discussion
3. Every issue has a milestone assigning it to a release
4. Proposed changes to the proposal should be in the form of a pull request
5. Before a CSL _release_ is issued, there will be a four week comments period.

**Comment by denismaier** [comment]
The essence here seems to be to use individual files for each proposal. This doesn't seem to be the current opinion of the OP and the development process is currently discussed elsewhere.  I propose to close this for now. Ok?

**Comment by bdarcus** [comment]
Yes, please close.

**Comment by denismaier** [comment]
I can't. (Just in case you mean me @bdarcus) @adam3smith Can you close this issue if that's ok for you?
