### ISSUE TITLE
Proposed change to <names> behavior

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#7]
The current behavior if multiple creator variables are passed inside `<names>` is to render a `<name>` object for each name type, separated by the `delimiter` argument passed to `<names>`. This behavior is limiting, because it makes it impossible to include multiple creator types in one name string. This means that rules for `and` and `et-al` cannot be applied to lists containing multiple author types. 

For example, in APA, if a book has both an editor and a translator, chapters would be cited as:
… In A. Jones (Ed.), & B. Smith (Trans.), _A great book_ 

or, in the case of multiple editors/translators:
… In A. Jones (Ed.), B. Johnson (Ed.), & B. Smith (Trans.), _A great book_ 

Another APA example--it also regards authors and illustrators as both "authors" and asks that both be listed together (without labels). 

This gets particularly important if we want to fully support media citations in APA. There, APA wants something like the second example, listing each creator with their role as one list (and following `and` and `et-al` rules:
Jones, A. (Producer), Johnson, B. (Producer), Allen, C. (Writer), & Smith, B. (Director). (2018). _A great TV episode_ …

These structures aren't currently possible in APA. You can hard-code `", &amp; "` as the `delimiter` on `names`, but this won't consistently produce a list of (potentially labeled) names with only one &.

A more flexible approach would be for each `<names>` node to render all of creators given in `variable` in one string—i.e., instead of `variable="editor translator"` producing two `name` strings—one for editors and one for translators, it would produce one `name` string including all of the creators that are either editors or translators. Collapsing of creators (like for `editortranslator`) could be done on a name-by-name basis). Besides the additional flexibility, personally, I would find this behavior much more intuitive. (The current behavior can be easily replicated if needed using `<group>`.)

**Comment by bdarcus** [comment]
So what would the proposed change be, specifically?

And I'd be curious how it would work in another style, maybe that handled
the grouping and rendering of the role descriptors differently? Maybe
Chicago?

**Comment by bwiernik** [comment]
The specific change is to change: http://docs.citationstyles.org/en/stable/specification.html#names
> The `cs:names` rendering element outputs the contents of one or more name variables (selected with the required `variable` attribute), each of which can contain multiple names (e.g. the “author” variable contains all the author names of the cited item). If multiple variables are selected (separated by single spaces, see example below), each variable is independently rendered in the order specified, with one exception: when the selection consists of “editor” and “translator”, and when the contents of these two name variables is identical, then the contents of only one name variable is rendered. In addition, the “editortranslator” term is used if the `cs:names` element contains a `cs:label` element, replacing the default “editor” and “translator” terms (e.g. resulting in “Doe (editor & translator)”). The delimiter attribute may be set on `cs:names` to separate the names of the different name variables (e.g. the semicolon in “Doe, Smith (editors); Johnson (translator)”).

To something like:
> The `cs:names` rendering element outputs the contents of one or more name variables (selected with the required `variable` attribute), each of which can contain multiple names (e.g. the “author” variable contains all the author names of the cited item). If multiple variables are selected (separated by single spaces, see example below), the names for all selected variables are concatenated in the order specified. Identical names from multiple name variables are rendered only once. When an identical name is both an "editor" and a "translator", the “editortranslator” term is used if the `cs:names` element contains a `cs:label` element, replacing the default “editor” and “translator” terms (e.g. resulting in “Doe (editor & translator)”). Other terms for identical names are concatenated using the `and` and `delimiter` attributes passed to `cs:label`. 

This change replaces the current names behavior that is essentially identical to `group` with behavior that can accommodate APA-style multi-type creator strings.

Compared to APA's format:
> Dick, L. (Writer), & Yaitanes, G. (Director). (2009). Simple explanation [Television series episode]. In P. Attanasio (Executive producer), House, M.D. Los Angeles, CA: Fox Broadcasting.

Chicago has a simpler format that just renders each role as a separate string:
> House, M.D. “Simple Explanation.” Directed by Greg Yaitanes. Written by Leonard Dick. Fox Broadcasting, April 6 2009.

MLA is similar: 
> “Simple Explanation.” House, M.D.: The Complete Fifth Season. Writ. Leonard Dick. Dir. Greg Yaitanes. Fox Broadcasting, 2009. DVD.

These can be accomplished using a `group` with `delimiter=". "`

**Comment by adam3smith** [comment]
> These can be accomplished using a group with delimiter=". "

but --apart from being a good deal more tedious with groups of 3+ creators -- that breaks the `editortranslator` functionality.

**Comment by bwiernik** [comment]
Perhaps a new attribute for `names` to do combined versus sequential lists of names? That way all of the existing behavior can stay unchanged?

**Comment by zuphilip** [comment]
> Perhaps a new attribute for names to do combined versus sequential lists of names?

:+1: For example an attribute `multiple` with values as `one-after-each-other` (default) and `combined`.

---

I tried to analyze the current usage of multiple variables in `names`. Searching the regex `<names variable="(\w+\s[^"]+)"` in a up-to-date styles repository leads to 851 hits in 486 styles. The most used combinations are:
* "editor translator" with 746 hits
* "translator editor" with 32 hits
* "editor collection-editor... with 36 hits


<details>

```
* 746 times "editor translator"
* 11 times "editor translator container-author"
* 17 times "editor collection-editor editorial-director director translator"
* 4 times "editor collection-editor"
* 1 time "editor collection-editor editorial-director"
* 1 time "editor collection-editor editorial-director translator"
* 2 times "editor collection-editor editorial-director director"
* 11 times "editor collection-editor director editorial-director"
* 4 times "editor container-author"
* 1 time "editor director"
* 32 times "translator editor"
* 5 times "translator editor container-author"
* 1 time "interviewer illustrator container-author"
* 5 times "author editor"
* 1 time "author director"
* 1 time "author interviewer"
* 2 times "interviewer editor translator"
* 6 times "composer editor"
```
</details>

**Comment by bwiernik** [comment]
That would work well, I think. When `multiple="combined"`:
1. All of the variables are rendered in 1 `name` element 
1. Names are arranged by variable in the order specified in `variables`
1. Identical names for multiple variables are combined/collapses and only rendered once
1. Labels for collapsed identical names are combined using `delimiter`, `and`, and `delimiter-precedes-last` attributes applied to `label`

**Comment by fbennett** [comment]
Just in case this might get lost in the shuffle, an alternative to the proposals here was [mentioned on CSL Discourse](https://discourse.citationstyles.org/t/more-flexible-editortranslator-behavior/1498/9?u=frank_bennett) and seems to have found favor.

**Comment by bwiernik** [comment]
@denismaier @bdarcus 

Succinct proposal for 2.0:

1. Make `editortranslator` an explicitly callable name variable that can be used in `if`, `substitute`, etc.
1. Add `multiple` argument to `names` with options `multiple="sequential"` (default, current behavior) and `multiple="combined"`, which indicates
    1. Render all variables in `names` in one `name` element
    1. Names are arranged by variable in the order specified in variables
    1. Identical names for multiple variables are collapsed and only rendered once (like `editortranslator` behavior.
    1. Labels for collapsed identical names are combined using `delimiter`, `and`, and `delimiter-precedes-last` attributes applied to label.

**Comment by denismaier** [comment]
Would this also cover https://github.com/citation-style-language/schema/issues/128 ???

**Comment by bwiernik** [comment]
In that the linked issue is my first point above, yes.
